version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - kafkanet
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    networks:
      - kafkanet
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tasks:5:1"
    depends_on:
      - zookeeper

  postgre:
    image: postgres
    networks:
      - kafkanet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./createTasksTable.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx
    networks:
      - kafkanet
    ports:
      - "8080:90"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


  taskmanager1:
    image: taskmanager:latest
    networks:
      - kafkanet
    ports:
      - "8001:8080"
    environment:
      POSTGRE_URL: jdbc:postgresql://postgre:5432/db
      KAFKA_CONSUMER_SERVERS: kafka:9092
      KAFKA_PRODUCER_SERVERS: kafka:9092

  taskmanager2:
    image: taskmanager:latest
    networks:
      - kafkanet
    ports:
      - "8002:8080"
    environment:
      POSTGRE_URL: jdbc:postgresql://postgre:5432/db
      KAFKA_CONSUMER_SERVERS: kafka:9092
      KAFKA_PRODUCER_SERVERS: kafka:9092
  taskmanager3:
    image: taskmanager:latest
    networks:
      - kafkanet
    ports:
      - "8003:8080"
    environment:
      POSTGRE_URL: jdbc:postgresql://postgre:5432/db
      KAFKA_CONSUMER_SERVERS: kafka:9092
      KAFKA_PRODUCER_SERVERS: kafka:9092
  taskmanager4:
    image: taskmanager:latest
    networks:
      - kafkanet
    ports:
      - "8004:8080"
    environment:
      POSTGRE_URL: jdbc:postgresql://postgre:5432/db
      KAFKA_CONSUMER_SERVERS: kafka:9092
      KAFKA_PRODUCER_SERVERS: kafka:9092
  taskmanager5:
    image: taskmanager:latest
    networks:
      - kafkanet
    ports:
      - "8005:8080"
    environment:
      POSTGRE_URL: jdbc:postgresql://postgre:5432/db
      KAFKA_CONSUMER_SERVERS: kafka:9092
      KAFKA_PRODUCER_SERVERS: kafka:9092

networks:
  kafkanet:
    name: kafkanet
